### ISSUE TITLE
"WARN: An attempt was made to change package_name ..." on RHEL

### ISSUE THREAD

**Issue by Poohblah** [tas50/chef-sssd_ldap#22]
When converging on an RHEL system, the following warning is generated:
```
[2016-04-15T17:57:03-06:00] WARN: An attempt was made to change package_name from "libsss-sudo" to nil by calling package_name(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at /tmp/d20160415-13551-3jq472/cookbook_artifacts/sssd_ldap-a2023df166d1e57c14654fe0bf295db927c0bd4e/recipes/default.rb:26:in `block in from_file' at /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
```
This is just noise, since this resource isn't even run on RHEL, so the warning should be eliminated.

**Comment by tas50** [comment]
Fixed in 642377413ff943976dad5238d55a8d271f4279df
